# Generated by Django 3.0.2 on 2020-01-09 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cinema name', max_length=256, verbose_name='Name')),
                ('address', models.TextField(help_text='Cinema address', max_length=256, verbose_name='Address')),
                ('city', models.CharField(help_text='City name', max_length=128, verbose_name='City')),
                ('telephone', models.CharField(help_text='Telephone regexp !!!', max_length=20, verbose_name='Telephone')),
                ('geo_lat', models.SmallIntegerField(verbose_name='Latitude')),
                ('geo_lon', models.SmallIntegerField(verbose_name='Longitude')),
                ('pic_url', models.URLField(help_text='Cinema photo', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Film title', max_length=256, unique=True, verbose_name='Title')),
                ('description', models.TextField(help_text='Film description', max_length=512, verbose_name='Description')),
                ('date', models.DateField(auto_now_add=True, help_text='Film date', verbose_name='Date')),
                ('duration', models.IntegerField(help_text='Film duration', verbose_name='Duration')),
                ('genre', models.PositiveIntegerField(choices=[(1, 'Comedy'), (2, 'Action'), (3, 'Historical'), (4, 'Sci-Fi'), (5, 'Horror')], default=2, help_text='Film genre', verbose_name='Genre')),
                ('pic_url', models.URLField(help_text='Film poster', verbose_name='Picture')),
                ('video_url', models.URLField(help_text='Film trailer', verbose_name='Trailer')),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server_app.Cinema', verbose_name='Cinema ID')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server_app.Film', verbose_name='Film ID')),
            ],
        ),
    ]
