# Generated by Django 3.0.2 on 2020-01-11 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва кінотеатру', max_length=256, verbose_name='Назва')),
                ('address', models.TextField(help_text='Адреса кінотеатру', max_length=256, verbose_name='Адреса')),
                ('city', models.CharField(max_length=128, verbose_name='Місто')),
                ('telephone', models.CharField(help_text='Контактний телефон', max_length=20, verbose_name='Телефон')),
                ('geo_lat', models.FloatField(verbose_name='Координати: широта')),
                ('geo_lon', models.FloatField(verbose_name='Координати: довгота')),
                ('pic_url', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Кінотеатр',
                'verbose_name_plural': 'Кінотеатри',
                'ordering': ['-city'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Назва фільму', max_length=256, verbose_name='Назва')),
                ('description', models.TextField(help_text='Опис фільму', max_length=512, verbose_name='Опис')),
                ('date', models.DateField(auto_now_add=True, help_text="Дата прем'єри", verbose_name='Дата')),
                ('duration', models.IntegerField(help_text='Тривалість фільму', verbose_name='Тривалість')),
                ('genre', models.PositiveIntegerField(choices=[(1, 'Comedy'), (2, 'Action'), (3, 'Historical'), (4, 'Sci-Fi'), (5, 'Horror')], default=2, help_text='Жанр фільму', verbose_name='Жанр')),
                ('video_url', models.URLField(help_text='Посилання на YouTube', verbose_name='Трейлер')),
                ('pic_url', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Фільм',
                'verbose_name_plural': 'Фільми',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='Час показу', verbose_name='Час')),
                ('date', models.DateField(help_text='Дата показу', verbose_name='Дата')),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server_app.Cinema', verbose_name='Cinema ID')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server_app.Film', verbose_name='Film ID')),
            ],
            options={
                'verbose_name': 'Розклад',
                'verbose_name_plural': 'Розклад',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Місце у залі', max_length=32, verbose_name='Місце')),
                ('code', models.CharField(max_length=1024, verbose_name='Код')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Returned'), (2, 'Active'), (3, 'Canceled')], default=2, help_text='Статус квитка', verbose_name='Статус')),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server_app.Cinema', verbose_name='Cinema')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server_app.Film', verbose_name='Film ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Білети',
                'verbose_name_plural': 'Білет',
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server_app.Cinema', verbose_name='Cinema ID')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server_app.Film', verbose_name='Film ID')),
            ],
            options={
                'verbose_name': 'Афіша',
                'verbose_name_plural': 'Афіши',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Найменування залу', max_length=128, verbose_name='Назва залу')),
                ('hall_json', models.TextField(verbose_name='JSON')),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server_app.Cinema', verbose_name='Cinema ID')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Зали',
                'ordering': ['-name'],
            },
        ),
    ]
