# Generated by Django 3.0.2 on 2020-01-09 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={'ordering': ['-city'], 'verbose_name': 'Кінотеатр', 'verbose_name_plural': 'Кінотеатри'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-title'], 'verbose_name': 'Фільм', 'verbose_name_plural': 'Фільми'},
        ),
        migrations.AlterModelOptions(
            name='poster',
            options={'verbose_name': 'Афіша', 'verbose_name_plural': 'Афіши'},
        ),
        migrations.AlterField(
            model_name='cinema',
            name='geo_lat',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='geo_lon',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Time')),
                ('date', models.DateField(verbose_name='Date')),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server_app.Cinema', verbose_name='Cinema ID')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server_app.Film', verbose_name='Film ID')),
            ],
            options={
                'verbose_name': 'Розклад',
                'verbose_name_plural': 'Розклад',
                'ordering': ['-date'],
            },
        ),
    ]
