# Generated by Django 3.0.2 on 2020-01-09 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0002_auto_20200109_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва залу', max_length=128, verbose_name='Назва залу')),
                ('hall_json', models.TextField(verbose_name='JSON')),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server_app.Cinema', verbose_name='Cinema')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Зали',
                'ordering': ['-name'],
            },
        ),
    ]
