# Generated by Django 3.0.2 on 2020-01-09 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server_app', '0003_hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=32, verbose_name='Місце')),
                ('code', models.CharField(max_length=1024, verbose_name='Код')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Returned'), (2, 'Active'), (3, 'Canceled')], default=2, verbose_name='Статус')),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server_app.Cinema', verbose_name='Cinema')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server_app.Film', verbose_name='Film ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Білети',
                'verbose_name_plural': 'Білет',
            },
        ),
    ]
