# Generated by Django 3.0.2 on 2020-01-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
