# Generated by Django 3.0.2 on 2020-01-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0005_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='code',
        ),
    ]
