# Generated by Django 3.0.2 on 2020-01-11 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0006_remove_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024, verbose_name='Код'),
            preserve_default=False,
        ),
    ]
