# Generated by Django 3.0.2 on 2020-01-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0008_auto_20200111_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='pic_url',
            field=models.FileField(upload_to=''),
        ),
    ]
