# Generated by Django 3.0.2 on 2020-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0009_auto_20200113_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='pic_url',
            field=models.FileField(upload_to='film_pic/'),
        ),
    ]
