# Generated by Django 3.0.2 on 2020-01-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0011_auto_20200113_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='pic_url',
            field=models.ImageField(upload_to='film/poster/'),
        ),
    ]
