# Generated by Django 3.0.2 on 2020-01-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0012_auto_20200113_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='pic_url',
            field=models.ImageField(upload_to='cinema/pic/', verbose_name='Зображення кінотеатру'),
        ),
        migrations.AlterField(
            model_name='film',
            name='pic_url',
            field=models.ImageField(upload_to='film/poster/', verbose_name='Постер фільму'),
        ),
    ]
