# Generated by Django 3.0.2 on 2020-02-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0014_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ціна'),
        ),
    ]
