# Generated by Django 3.0.2 on 2020-02-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0015_timeline_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='timeline_id',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='server_app.Timeline', verbose_name='Сеанс'),
            preserve_default=False,
        ),
    ]
