# Generated by Django 3.0.2 on 2020-02-27 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0017_auto_20200227_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['-datetime'], 'verbose_name': 'Розклад', 'verbose_name_plural': 'Розклад'},
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='time',
        ),
        migrations.AddField(
            model_name='timeline',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час'),
            preserve_default=False,
        ),
    ]
