# Generated by Django 3.0.2 on 2020-03-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0019_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='hall_id',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.DO_NOTHING, to='server_app.Hall', verbose_name='Hall ID'),
            preserve_default=False,
        ),
    ]
