# Generated by Django 3.0.2 on 2020-04-06 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0020_timeline_hall_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'verbose_name': 'Розклад', 'verbose_name_plural': 'Розклад'},
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='datetime',
        ),
        migrations.AddField(
            model_name='timeline',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Дата показу', verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Час показу', verbose_name='Час'),
        ),
    ]
